---
name: unit-tests

on:
    pull_request:
    push:
        branches: [main]

jobs:
  ci:
    name: "run linting"
    strategy:
      fail-fast: true
      matrix:
        os:  ["ubuntu-latest", "windows-latest", "macOS-latest"]
        go:  ["1.22.x", "1.23.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: "checkout"
      uses: actions/checkout@v2
    - name: "fetch unshallow"
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: "test"
      run: "go test ./..."
